services:
  - type: web
    name: aplicacion-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn miweb.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DISABLE_COLLECTSTATIC
        value: "1"